name: Static analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test:ci

      # This is the command run in vercel. Better to also run it here to surface any issues. It runs linter, type checking and building.
      - name: Create test build
        run: npm run build
